src/Entity/Friend.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FriendRepository")
 */
class Friend
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ProfilSolo", mappedBy="friends")
     */
    private $profilSolos;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Chat", mappedBy="friend", cascade={"persist", "remove"})
     */
    private $chat;

    public function __construct()
    {
        $this->profilSolos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|ProfilSolo[]
     */
    public function getProfilSolo(): Collection
    {
        return $this->profilSolos;
    }

    public function addProfilSolo(ProfilSolo $profilSolos): self
    {
        if (!$this->profilSolos->contains($profilSolos)) {
            $this->profilSolos[] = $profilSolos;
            $profilSolos->addFriend($this);
        }

        return $this;
    }

    public function removeProfilSolo(ProfilSolo $profilSolos): self
    {
        if ($this->profilSolos->contains($profilSolos)) {
            $this->profilSolos->removeElement($profilSolos);
            $profilSolos->removeFriend($this);
        }

        return $this;
    }

    public function getChat(): ?Chat
    {
        return $this->chat;
    }

    public function setChat(Chat $chat): self
    {
        $this->chat = $chat;

        // set the owning side of the relation if necessary
        if ($chat->getFriend() !== $this) {
            $chat->setFriend($this);
        }

        return $this;
    }
}

src/Entity/ProfilClub.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfilClubRepository")
 */
class ProfilClub
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nameClub;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cityClub;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logoClub;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionClub;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Sport", inversedBy="profilClubs")
     */
    private $sports;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\GeneralChatClub", mappedBy="profilClub")
     */
    private $generalChatClub;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PrivateChatClub", mappedBy="profilClub", cascade={"persist", "remove"})
     */
    private $privateChatClub;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="profilClubs")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Event", mappedBy="creatorClub")
     */
    private $events;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProfilSolo", mappedBy="profilClub", fetch="EAGER")
     */
    private $profilSolos;

    public function __construct()
    {
        $this->sports = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->profilSolos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameClub(): ?string
    {
        return $this->nameClub;
    }

    public function setNameClub(string $nameClub): self
    {
        $this->nameClub = $nameClub;

        return $this;
    }

    public function getCityClub(): ?string
    {
        return $this->cityClub;
    }

    public function setCityClub(string $cityClub): self
    {
        $this->cityClub = $cityClub;

        return $this;
    }
    /* For logo file*/

    public function getLogoClub(): ?string
    {
        return $this->logoClub;
    }

    public function setLogoClub(string $logoClub): self
    {
        $this->logoClub = $logoClub;

        return $this;
    }

    public function getDescriptionClub(): ?string
    {
        return $this->descriptionClub;
    }

    public function setDescriptionClub(?string $descriptionClub): self
    {
        $this->descriptionClub = $descriptionClub;

        return $this;
    }

    /**
     * @return Collection|Sport[]
     */
    public function getSport(): Collection
    {
        return $this->sports;
    }

    public function setSport(Sport $sports): self
    {
        if (!$this->sports->contains($sports)) {
            $this->sports[] = $sports;
        }

        return $this;
    }

    public function removeSport(Sport $sports): self
    {
        if ($this->sports->contains($sports)) {
            $this->sports->removeElement($sports);
        }

        return $this;
    }

    public function getGeneralChatClub(): ?GeneralChatClub
    {
        return $this->generalChatClub;
    }


    public function setGeneralChatClub(GeneralChatClub $generalChatClub): self
    {
        $this->generalChatClub = $generalChatClub;

        // set the owning side of the relation if necessary
        if ($generalChatClub->getProfilClub() !== $this) {
            $generalChatClub->setProfilClub($this);
        }

        return $this;
    }

    public function getPrivateChatClub(): ?PrivateChatClub
    {
        return $this->privateChatClub;
    }

    public function setPrivateChatClub(PrivateChatClub $privateChatClub): self
    {
        $this->privateChatClub = $privateChatClub;

        // set the owning side of the relation if necessary
        if ($privateChatClub->getProfilClub() !== $this) {
            $privateChatClub->setProfilClub($this);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addProfilClub($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeProfilClub($this);
        }

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setCreatorClub($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getCreatorClub() === $this) {
                $event->setCreatorClub(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ProfilSolo[]
     */
    public function getProfilSolos(): Collection
    {
        return $this->profilSolos;
    }

    public function addProfilSolo(ProfilSolo $profilSolo): self
    {
        if (!$this->profilSolos->contains($profilSolo)) {
            $this->profilSolos[] = $profilSolo;
            $profilSolo->setProfilClub($this);
        }

        return $this;
    }

    public function removeProfilSolo(ProfilSolo $profilSolo): self
    {
        if ($this->profilSolos->contains($profilSolo)) {
            $this->profilSolos->removeElement($profilSolo);
            // set the owning side to null (unless already changed)
            if ($profilSolo->getProfilClub() === $this) {
                $profilSolo->setProfilClub(null);
            }
        }

        return $this;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Comment;
use App\Entity\Event;
use App\Entity\ParticipationLike;
use App\Entity\ProfilClub;
use App\Entity\ProfilSolo;
use App\Form\CommentType;
use App\Form\EventType;
use App\Repository\CommentRepository;
use App\Repository\EventRepository;
use App\Repository\ParticipationLikeRepository;
use App\Repository\ProfilClubRepository;
use App\Services\GetUserClub;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use DateTime;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="event", methods={"GET", "POST"}, options={"expose"=true})
     * @param GetUserClub $club
     * @return Response
     * @IsGranted("ROLE_USER")
     */
    public function index(GetUserClub $club, ProfilClubRepository $profilClubRepository): Response
    {

        $thisClub = $profilClubRepository->find($club->getClub());
        $ema = $this->getDoctrine()->getManager();
        $events = $ema->getRepository(Event::class)
            ->findBy(['creatorClub'=>$club->getClub()]);
        return $this->render('event/index.html.twig', [
            'events' => $events,
            'profil_club'=>$thisClub
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     * @param Request $request
     * @param GetUserClub $club
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @IsGranted("ROLE_CLUBER")
     */
    public function new(
        Request $request,
        GetUserClub $club,
        ProfilClubRepository $profilClubRepository,
        EntityManagerInterface $entityManager
    ): Response {
        $thisClub = $profilClubRepository->find($club->getClub());
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $event->setCreatorClub($club->getClub());
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event');
        }

        return $this->render('event/new.html.twig', [

            'form' => $form->createView(),
            'profil_club'=>$thisClub
        ]);
    }

    /**
     * @Route("/{id}", name="event_show",  methods={"POST", "GET"}, options={"expose"=true})
     * @param EventRepository $eventRepository
     * @param Event $event
     * @param Request $request
     * @param CommentRepository $comments
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @throws \Exception
     * @IsGranted("ROLE_USER")
     */
    public function show(
        EventRepository $eventRepository,
        Event $event,
        Request $request,
        CommentRepository $comments,
        ProfilClubRepository $profilClubRepository,
        GetUserClub $club,
        EntityManagerInterface $entityManager
    ) : Response {

        $thisClub = $profilClubRepository->find($club->getClub());
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $commentsList = $comments->findBy(['event'=>$event]);

        $creatorSolo = $this->getUser()->getProfilSolo();
        $participants = $this->getParticipants($event);


        if ($form->isSubmitted() && $form->isValid() && ($form['content']->getData()) != null) {
            $comment->setContent($_POST['comment']['content']);
            $comment->setDateComment(new DateTime('now'));
            $comment->setEvent($event);
            $comment->setProfilSolo($creatorSolo);
            $entityManager->persist($comment);
            $entityManager->flush();
        }

        return $this->render('event/show.html.twig', [
            'events' => $eventRepository->findAll(),
            'event' => $event,
            'form' => $form->createView(),
            'comments' => $commentsList,
            'participants' => $participants,
            'profil_club'=>$thisClub
        ]);
    }

    /**
     * @param Event $event
     * @return array
     */
    public function getParticipants(Event $event)
    {

        $entityManager = $this->getDoctrine()->getRepository(ParticipationLike::class);
        $participantList = $entityManager->findBy([
            'event'=> $event
        ]);

        $list = [];
        foreach ($participantList as $participant) {
            $list[]= [
                    'firstname' => $participant->getUser()->getProfilSolo()->getFirstname(),
                    'lastname' => $participant->getUser()->getProfilSolo()->getLastname(),
                    'avatar' => $participant->getUser()->getProfilSolo()->getAvatar(),
                ];
        }
            return $list;
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Event $event
     * @return Response
     * @IsGranted("ROLE_CLUBER")
     */
    public function edit(
        Request $request,
        Event $event,
        EntityManagerInterface $entityManager,
        GetUserClub $club
    ): Response {

        $thisClub = $entityManager->getRepository(ProfilClub::class)
            ->find($club->getClub());
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
            'profil_club'=>$thisClub
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     * @param Request $request
     * @param Event $event
     * @param EntityManagerInterface $entityManager
     * @return Response
     * @IsGranted("ROLE_CLUBER")
     */
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event');
    }

    /**
     * Allows you to participate and no longer participate
     * @Route("/{id}/participe", name="event_participe")
     * @param Event $event
     * @param ObjectManager $manager
     * @param ParticipationLikeRepository $participationRepo
     * @return Response
     * @IsGranted("ROLE_USER")
     */
    public function participation(
        Event $event,
        ObjectManager $manager,
        ParticipationLikeRepository $participationRepo
    ) : Response {
        $user = $this->getUser();

        if (!$user) {
            return $this->json([
                'code'=>403,
                'message'=>"Connectez vous"
            ], 403);
        }

        if ($event->isParticipationByUser($user)) {
            $participationLike = $participationRepo->findOneBy([
                'event'=>$event,
                'user'=>$user
            ]);

            $manager->remove($participationLike);
            $manager->flush();

            return $this->json([
                'code'=>200,
                'message'=>"Participation supprimée",
                'participationLikes'=> $participationRepo->count(['event'=> $event]),
                ], 200);
        }

        $participationLike = new ParticipationLike();
        $participationLike->setEvent($event)
            ->setUser($user);

        $manager->persist($participationLike);
        $manager->flush();


        return $this->json([
            'code' => 200,
            'message' => 'Participation acceptée',
            'participationLikes'=> $participationRepo->count(['event'=> $event])
        ], 200);

        if ($this->getUser()->getRoles() === ['ROLE_REGISTERED']) {
            return $this->render('registration/choiceTypeRegister.html.twig');
        }
        return $this->render('event/index.html.twig');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="delete"></button>
</form>

templates/event/_form.html.twig
{{ form_start(form)}}
<div class="form_group1">

    <label for="{{ form.nameEvent.vars.id }}"></label>
    {{ form_widget(form.nameEvent) }}
    <hr>

    {% do form.nameEvent.setRendered %}
    {{ form_errors(form.nameEvent) }}
    {{ form_widget(form.nameEvent) }}
    <hr>
</div>
<div class="date_time">
    <img src="{{ asset("build/images/date.svg")}}" alt="calendrier" class="img-date-heure">
    <img src="{{ asset("build/images/time.svg")}}" alt="horloge" class="img-date-heure">
</div>
<div class="form_group">
    {{ form_widget(form.dateEvent) }}
    {{ form_widget(form.timeEvent) }}
</div>
<div  class="sport_choice">
    {{ form_errors(form.sport) }}
    {{ form_widget(form.sport) }}
</div>
<div class="form_group2">
    {{ form_errors(form.description) }}
    {{ form_widget(form.description) }}
</div>
<div class="form_group3">
    {{ form_errors(form.levelEvent) }}
    {{ form_widget(form.levelEvent) }}
</div>
<div class="form_group4">
    {{ form_errors(form.participantLimit) }}
    {{ form_widget(form.participantLimit) }}
</div>
<div class="form_group5">
    {{ form_errors(form.placeEvent) }}
    {{ form_widget(form.placeEvent) }}
</div>

<button class="btn">{{ button_label|default('') }}</button>
<div class="alert alert-danger">{{ form_rest(form) }}</div>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking | Modifier l'évenement{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('edit_events') }}
{% endblock %}
{% block body %}
    {% include 'navbar/_navbar.html.twig' %}
    <div class="edit">
    {{ include('event/_form.html.twig', {'button_label': ' '}) }}

        <button class="return"><a href="{{ path('event') }}"><img src="{{ asset("build/images/return.svg")}}" alt="retour" class="icons"></a></button>

    {{ include('event/_delete_form.html.twig') }}
    </div>
{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('edit_events') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking | Événements {% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('new_events') }}
{% endblock %}
{% block body %}
    {% include 'navbar/_navbar.html.twig' %}
    <div class="index_event">

        {% for event in events %}
            <button class="card_button"><a href="{{ path('event_show', {'id': event.id}) }}">
           <div class="card_events">
                <p class="date_time">{{ event.dateEvent ? event.dateEvent|date('d-m-Y') : '' }} | {{ event.timeEvent ? event.timeEvent|date('H:i') : '' }}</p>
                <p class="n_event">{{ event.nameEvent }}</p>
                <p class="level_ni">Niveau : {{ event.levelEvent }}</p>
           </div>
                </a>
            </button>
        {% else %}
            <h1>Aucun événement trouvé. Créez votre premier événement.</h1>

        {% endfor %}
    {% if is_granted('ROLE_CLUBER') %}
    <button class="add"><a href="{{ path('event_new') }}"><img src="{{ asset("build/images/add.svg")}}" alt="edit" class="icons"></a></button>
    {% endif %}
    </div>

{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('new_events') }}
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gruppetto | Nouvel événement {% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('new_events') }}
{% endblock %}
{% block body %}
    {% include 'navbar/_navbar.html.twig' %}
    <div class="new">
        {{ include('event/_form.html.twig') }}
        <button class="return1"><a href="{{ path('event') }}"><img src="{{ asset("build/images/return.svg")}}" alt="retour" class="icons"></a></button>
    </div>
{% endblock %}
 {% block javascripts %}
     {{ encore_entry_script_tags('new_events') }}
 {% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking | {{event.nameEvent}} {% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('new_events') }}
{% endblock %}
{% block body %}
    {% include 'navbar/_navbar.html.twig' %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <div class="show_events">
        <h1>{{ event.nameEvent }}</h1>
        <hr>
        <p class="date_time_show">{{ event.dateEvent ? event.dateEvent|date('d-m-Y') : '' }} | {{ event.timeEvent ? event.timeEvent|date('H:i') : '' }} | {{ event.placeEvent }}</p>
        <p class="date_time_show">Entraîneur : JOhn JOe</p>
        <p class="levl_n">Niveau : {{ event.levelEvent }}</p>
        <p class="descript">{{ event.description }}</p>

        <div class="participation">

            {% if is_granted('ROLE_CLUBER') %}
                <p class="nb_participant">N° de particpant : {{ event.participationLikes | length }}/{{ event.participantLimit }} </p>
            {% else %}
            <a href="{{ path('event_participe', {'id' : event.id}) }}" class="btn-link js-participe">
                {% if app.user and event.isParticipationByUser(app.user) %}
                    <i class="fas fa-check-circle"></i>
                {% else %}
                    <i class="far fa-check-circle"></i>
                {% endif %}
                {% if event.participantLimit >  event.participationLikes | length  %}
                <span class="js-participationLikes">{{ event.participationLikes | length }}</span> / {{ event.participantLimit }}
                {% else %}
                    <p class="limit">Limite atteinte : {{ event.participationLikes | length }}/{{ event.participantLimit }}</p>
                {% endif %}
            </a>
            {% endif %}
            <div id="participants">
                {% for participant in participants %}
                    <img src="{{ participant.avatar }}" alt="{{ participant.firstname }} {{ participant.lastname }}">
                {% endfor %}
            </div>

            <h2>Commentaire :</h2>
            <hr>
            <div class="scroll_comment">
                    {% for comment in comments %}

                    <div class="comment">
                        <ul>
                            <li>
                            <p class="name_comment">  {{ comment.profilSolo.lastName}}  {{ comment.profilSolo.firstName}} <br></p>
                            <p class="content_comment"> {{ comment.content }}</p>
                       </li>
                        </ul>

                    </div>

                    {% endfor %}
            </div>
            <div class="add_comment">

                {{ form_start(form) }}
                {{ form_widget(form.content) }}
                 <button class="add_comment">{{ button_label|default('')}}<img src="{{ asset("build/images/send-message-icon.svg")}}" alt="send" class="icons"> </button>

                <div class="alert alert-danger">{{ form_rest(form) }}</div>
                {{ form_end(form) }}
            </div>


            {% if is_granted('ROLE_CLUBER') %}
            <button class="return"><a href="{{ path('event') }}"><img src="{{ asset("build/images/return.svg")}}" alt="retour" class="icons"></a></button>
            {{ include('event/_delete_form.html.twig') }}
            <button class="edit"><a href="{{ path('event_edit', {'id': event.id}) }}"><img src="{{ asset("build/images/btn-modif.svg")}}" alt="edit" class="icons"></a></button>
            {% else %}
                <button class="return_show"><a href="{{ path('event') }}"><img src="{{ asset("build/images/return.svg")}}" alt="retour" class="icons"></a></button>
            {% endif %}
        </div>
    </div>

{% endblock %}
{% block javascripts %}
         {{ encore_entry_script_tags('participation') }}
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
{% endblock %}